# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
   app.default_creds_path: "%env(string:HOME)%/.sumologic-creds.yml"
   app.sumologic_api_end_point: "https://api.sumologic.com/api/v1/search/jobs"
   #See https://help.sumologic.com/APIs/General-API-Information/Sumo-Logic-Endpoints-and-Firewall-Security

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $default_creds_path: "%app.default_creds_path%"
            $sumologic_api_end_point : "%app.sumologic_api_end_point%"

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Controller\ApiController:
        autowire: true
        arguments: 
            $default_creds_path : '%app.default_creds_path%'
            - $sumologic_api_end_point : '%app.sumologic_api_end_point%'

    # App\Controller\ConfigController:
    #  arguments:
    #         $credsPath: '%app.default_creds_path%'
